[project]
name = "query-gen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mlx>=0.22.0",
    "mlx-llm>=1.0.8",
    "numpy<2",
    "sentence-transformers>=3.3.1",
]
